name: Yad2 Scraper

on:
  schedule:
    - cron: '*/15 5-17 * * *'
  workflow_dispatch:

jobs:
  scraper:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
          cache: true

      - name: Setup Chrome
        id: chrome
        uses: browser-actions/setup-chrome@v1

      - name: Go mod download
        run: go mod download

      - name: Build
        run: go build -o scraper ./main.go

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "${{ secrets.GIT_CONFIG_EMAIL }}"

      - name: Run scraper
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          YAD2_BROWSER: "1"
          CHROME_PATH: ${{ steps.chrome.outputs.chrome-path }}
        run: |
          ./scraper

      - name: Push new json data if needed
        run: |
          if [ -f ./push_me ]; then
            echo "Pushing to GitHub..."
            git add .
            DATE=$(date +"%F, %H:%M:%S")
            git commit -m "updated data, $DATE" || echo "Nothing to commit"
            git push
          fi
